# Generated by Django 5.0.6 on 2024-07-09 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
